#!/usr/bin/env python3
"""Derive the light theme from the dark one.

Generating native_white.qss from brand.qss (rather than hand-writing it)
guarantees the two themes cover exactly the same selectors, so no widget on any
page is left unstyled when the light theme is active.

    python3 contrib/make_light_theme.py
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
STYLE = os.path.join(HERE, os.pardir, "src", "assets", "style")
SRC = os.path.join(STYLE, "brand.qss")
DST = os.path.join(STYLE, "native_white.qss")

# Dark value -> light value. The elevation model inverts: the dark theme puts
# dark cards on a black base, the light theme puts light-grey cards on white
# with white inputs recessed inside them.
COLORS = {
    # base surfaces
    "#000000": "#FFFFFF",   # page / tree / wizard+settings field base
    "#1a1b1d": "#F7F8FA",   # card
    "#1e1f20": "#F7F8FA",   # panel, search field, selected row
    "#101112": "#FFFFFF",   # field inside a card
    "#141414": "#F0F2F4",   # hover / alternating row
    "#151617": "#F7F8FA",   # chart plot surface
    "#202021": "#EDF0F3",   # disabled field border
    "#29292a": "#FFFFFF",   # secondary button face

    # borders
    "#2b2b2c": "#E2E6EB",
    "#232425": "#ECEFF2",
    "#444444": "#D5DBE2",
    "#35363a": "#FFFFFF",   # top "glass" edge highlight

    # text
    "#FFFFFF": "#16191D",   # primary text (white-on-accent restored below)
    "#979696": "#5A6472",
    "#7c7c7e": "#8B95A3",
    "#6a6a6c": "#98A1AD",
    "#5a5a5c": "#A9B0B9",
    "#8a93a3": "#6B7480",
    "#c6ccd6": "#2B313A",
    "#6f7887": "#8B95A3",

    # accent: the brand orange is kept; its hover/pressed shades darken
    # instead of lightening, which is what reads as "pressed" on a light base.
    "#ff7a34": "#E85A0C",
    "#e05a12": "#C94E0A",

    # status colours, darkened for contrast against light surfaces
    "#65cf6a": "#1F9D53",
    "#f18c8c": "#D64545",
    "#ffd25c": "#B8860B",
    "#4ea8ff": "#1E7FD4",
    "#f1584e": "#D33A2E",
    "#2d3f2e": "#C8E6CF",
    "#45302f": "#F3D2CE",

    # window chrome
    "#0d131a": "#F4F6F8",   # window / central widget
    "#0c111a": "#FFFFFF",   # navigation rail
    "#0b1017": "#F7F8FA",   # status bar
    "#1b2230": "#E2E6EB",
    "#1e2836": "#E8ECF1",
    "#141a24": "#FFFFFF",
    "#1a2331": "#EDF0F3",
    "#131a25": "#E2E6EB",
    "#39414f": "#C6CDD6",   # nav hover rail

    # wizard / ticker extras
    "#1f1f20": "#E8ECF1",   # wizard button pressed
    "#383733": "#E2E6EB",   # ticker separator
    "#99999a": "#5A6472",   # wizard secondary heading

    # Send screen specifics
    "#3a2a1c": "#FFD9C2",
    "#4a3320": "#FFC9A8",
    "#17181a": "#FFF4EE",
    "#0b0c0d": "#F0F2F4",
    "#0d0e0f": "#F4F6F8",
    "#5a3b23": "#FAD5BE",
    "#a68064": "#B58463",
}

RGBA = {
    "rgba(101, 207, 106, 0.15)": "rgba(31, 157, 83, 0.14)",
    "rgba(254, 104, 27, 0.15)": "rgba(254, 104, 27, 0.14)",
    "rgba(254, 104, 27, 0.12)": "rgba(254, 104, 27, 0.10)",
}

HEADER = """/* ============================================================
   Best Wallet — light theme ("Native (white)")
   ------------------------------------------------------------
   GENERATED by contrib/make_light_theme.py from brand.qss.
   Edit brand.qss (or the colour map in that script) and re-run;
   hand edits here are overwritten.

   Deriving it from the dark sheet keeps the two themes selector
   for selector identical, so every page stays fully styled.

   Palette:
     page background      #FFFFFF
     card / panel         #F7F8FA
     divider / border     #E2E6EB
     primary text         #16191D
     secondary text       #5A6472
     tertiary text        #8B95A3
     accent               #FE681B
     success              #1F9D53
   ============================================================ */"""


def remap(text):
    lookup = {k.lower(): v for k, v in COLORS.items()}
    # Single pass: a sequential search/replace would re-map values that the
    # mapping itself produces (several darks map onto #FFFFFF).
    text = re.sub(r'#[0-9A-Fa-f]{6}\b',
                  lambda m: lookup.get(m.group(0).lower(), m.group(0)),
                  text)
    for a, b in RGBA.items():
        text = text.replace(a, b)
    return text.replace("color: white;", "color: #2B313A;")


def restore_exceptions(text):
    """Put back the whites that are deliberate rather than themeable."""
    fixes = [
        # The QR code must stay on white or scanners lose contrast.
        ("""#ReceiveWidget ClickableLabel#qrCode {
    background: #16191D;""",
         """#ReceiveWidget ClickableLabel#qrCode {
    background: #FFFFFF;"""),
        # Text sitting on the orange accent stays white in both themes.
        ("""#SendWidget QPushButton#btnSend {
    background-color: #FE681B;
    color: #16191D;""",
         """#SendWidget QPushButton#btnSend {
    background-color: #FE681B;
    color: #FFFFFF;"""),
        ("""#ReceiveWidget QPushButton#btn_generateSubaddress {
    background-color: #FE681B;
    color: #16191D;""",
         """#ReceiveWidget QPushButton#btn_generateSubaddress {
    background-color: #FE681B;
    color: #FFFFFF;"""),
    ]
    for a, b in fixes:
        if a not in text:
            raise SystemExit(f"expected block not found while restoring:\n{a}")
        text = text.replace(a, b)

    # Dropdown rows: the mapped selection would have been white on white.
    text = text.replace(
        """    selection-background-color: #FFFFFF;
    selection-color: #16191D;""",
        """    selection-background-color: #FFF0E6;
    selection-color: #16191D;""")

    # Indicators ship as dark-theme artwork; the light sheet uses its own.
    for name in ("checkbox_checked", "checkbox_unchecked",
                 "radio_checked", "radio_unchecked"):
        text = text.replace(f"url(:/assets/images/{name}.svg)",
                            f"url(:/assets/images/{name}_light.svg)")

    # Highlighted text inside fields sits on the orange selection colour.
    text = text.replace(
        """    selection-background-color: #FE681B;""",
        """    selection-background-color: #FE681B;
    selection-color: #FFFFFF;""")
    return text


def main():
    src = open(SRC, encoding="utf-8").read()
    body = src.split("*/", 1)[1] if src.lstrip().startswith("/*") else src
    out = HEADER + restore_exceptions(remap(body))
    open(DST, "w", encoding="utf-8").write(out)

    leftover = sorted({c.lower() for c in re.findall(r'#[0-9A-Fa-f]{6}\b', out)}
                      - {v.lower() for v in COLORS.values()}
                      - {"#fe681b", "#ffffff", "#fff0e6", "#2b313a"})
    print(f"wrote {DST} ({len(out.splitlines())} lines)")
    print("unmapped colours remaining:", leftover or "none")


if __name__ == "__main__":
    main()
